### ISSUE TITLE
"internal_type" vs "internalType" in ABIs

### ISSUE THREAD

**Issue by cygnusv** [ApeWorX/ethpm-types#116] opened 2024-02-21 15:52 UTC
### Environment

- OS: macOS / linux / win
- Python Version: x.x.x
- `ape` and plugin versions:
0.7.7

```sh
$ ape --version
0.7.7


$ ape plugins list
Installed Plugins
  etherscan    0.7.0
  infura       0.7.0
  polygon      0.7.1
  solidity     0.7.1
```

### What went wrong?
We've been collecting deployment ABIs by reading `my_contract.contract_type.abi`, but we're noticing that with v0.7 there's some new elements that are different than before. Compare the output of v0.7.7:

```json
                "inputs": [
                        {
                            "name": "_token",
                            "type": "address",
                            "components": null,
                            "internal_type": "contract IERC20"
                        },
```

with previous versions (I think this was 0.6.19):

```json
                "inputs": [
                        {
                            "name": "_token",
                            "type": "address",
                            "internalType": "contract IERC20"
                        },
```

Two differences:
* `internalType` is now `internal_type``
* `"components": null` is present for non-tuple input/output items

My suspicion is that there may be a better, more standard way to get the ABI for a contract you just deployed? If not, was this change intentional?

**Comment by fubuloubu** [comment] 2024-02-21 16:18
transferred this to the proper repo

**Comment by derekpierre** [comment] 2024-07-08 15:35
@fubuloubu Any update on this issue?
- Was the change intentional?
- Are there any compatibility concerns with using the resulting different abi values with web3py?

**Comment by antazoey** [comment] 2024-07-08 17:56
I am unable to reproduce, please supply more info for reproduction steps.

Here is what I am doing:

```python
ct = project.TestContractSol.contract_type  # Using Ape but can get a ContractType anyway you want.
abi = ct.mode_dump()["abi"]
```

The ABI it is showing has the correct casing everywhere for internalType.

```
...
 {'type': 'function',
  'name': 'theAddress',
  'stateMutability': 'view',
  'inputs': [],
  'outputs': [{'name': '', 'type': 'address', 'internalType': 'address'}]}]
...
```

It works because of this code here: https://github.com/ApeWorX/ethpm-types/blob/main/ethpm_types/base.py#L10-L15

**Comment by derekpierre** [comment] 2024-07-08 18:05
Thanks for checking.

It seems that we are doing the following:
```python
def _get_abi(contract_instance: ContractInstance) -> ABI:
    """Returns the ABI of a contract instance."""
    contract_abi = list()
    for entry in contract_instance.contract_type.abi:
        contract_abi.append(entry.dict())
    return contract_abi
```

The `.dict()` call seems to now be deprecated ... 🤔 ... I guess we should be using `.model_dump()` instead?

**Comment by derekpierre** [comment] 2024-07-08 18:16
@antazoey ran some tests and that clarifies things - we caused the issue 😅 ! Thanks again for following-up. Much appreciated!

**Comment by antazoey** [comment] 2024-07-08 18:18
Oh yay!

Yes, `dict()` is deprecated but I can make the fix apply there as well.
Thank you!

**Closed** 2024-07-08 19:11 UTC
Labels: category: bug
